enum AuthOperation {
  none,
  signIn,
  register,
  googleSignIn,
  signOut,
  passwordReset,
  sendEmailVerification,
  refreshEmailVerification,
  createPassword,
  updatePassword,
  updateUserName,
  deleteAccount,
  linkGoogle,
  linkPassword,
}